known_keys = {
            "com.fontfont.colorfont.color": "FontFont foreground color",
            "com.fontfont.colorfont.colorbg": "FontFont background color",
            "com.fontfont.colorfont.colorpalette": "FontFont color palette",
            "com.fontfont.colorfont.layers": "FontFont color font layers",
            "com.fontfont.flott": "FontFont TrueType hinting data",
            
            "com.fontlab.v2.tth": "FontLab TrueType hinting data",
            "com.fontlab.ttprogram": "FontLab TrueType glyph programs",
            
            "com.schriftgestaltung.fontMaster.userData": "Glyphs app user data",
            "com.schriftgestaltung.gridSize": "Glyphs app grid size",
            "com.schriftgestaltung.useNiceNames": "Glyphs app nice name setting",
            "com.schriftgestaltung.weight": "Glyphs app weight name",
            "com.schriftgestaltung.weightValue": "Glyphs app weight value",
            
            "com.superpolator.editor.generateInfo": "Superpolator info",
            
            "com.typemytype.robofont.compileSettings.autohint": "RoboFont autohint setting",
            "com.typemytype.robofont.compileSettings.checkOutlines": "RoboFont check outlines",
            "com.typemytype.robofont.compileSettings.decompose": "RoboFont decompose setting",
            "com.typemytype.robofont.compileSettings.generateFormat": "RoboFont format",
            "com.typemytype.robofont.compileSettings.MacRomanFirst": "RoboFont Mac Roman setting",
            "com.typemytype.robofont.compileSettings.path": "RoboFont compile path",
            "com.typemytype.robofont.compileSettings.releaseMode": "RoboFont release mode",
            "com.typemytype.robofont.foreground.layerStrokeColor": "RoboFont foreground color",
            "com.typemytype.robofont.background.layerStrokeColor": "RoboFont background color",
            "com.typemytype.robofont.background.layerShow": "RoboFont background show",
            "com.typemytype.robofont.guides": "RoboFont guides",
            "com.typemytype.robofont.image": "RoboFont image data",
            "com.typemytype.robofont.italicSlantOffset": "RoboFont italic offset",
            "com.typemytype.robofont.layerOrder": "RoboFont layer order",
            "com.typemytype.robofont.mark": "RoboFont glyph mark colors",
            "com.typemytype.robofont.segmentType": "RoboFont segment type",
            "com.typemytype.robofont.shouldAddPointsInSplineConversion": "RoboFont TTF settings",
            "com.typemytype.robofont.sort": "RoboFont sort settings",
            
            "com.typesupply.AccentBuilder.defaultOffsets": "AccentBuilder default offsets",
            "com.typesupply.AccentBuilder.fixedGlyphs": "AccentBuilder fixed glyphs",
            "com.typesupply.AccentBuilder.guides": "AccentBuilder guides",
            "com.typesupply.AccentBuilder.ignoredGlyphs": "AccentBuilder ignored glyphs",
            "com.typesupply.AccentBuilder.synthesizedGlyphs": "AccentBuilder synthesized glyphs",
            "com.typesupply.AccentBuilder.toolVersion": "AccentBuilder version",
            "com.typesupply.MetricsMachine4.groupColors": "MetricsMachine group colors",
            "com.typesupply.ufocentral.openTypeNameWWSFamilyName": "UFOCentral WWS family name",
            "com.typesupply.ufocentral.openTypeNameWWSSubfamilyName": "UFOCentral WWS subfamily name",
            
            "org.robofab.fontlab.maskData": "FontLab glyph mask data",
            "org.robofab.fontlab.mark": "FontLab glyph hmark colors",
            "org.robofab.glyphOrder": "Robofab glyph order",
            "org.robofab.opentype.classes": "Robofab OpenType classes",
            "org.robofab.opentype.featureorder": "Robofab OpenType feature order",
            "org.robofab.opentype.features": "Robofab OpenType features",
            "org.robofab.postScriptHintData": "Robofab PostScript hints",
            
            "public.glyphOrder": "Glyph order",
            
        }